INSERT INTO Airline VALUES ('AA','United States','American Airlines Inc.');
INSERT INTO Airline VALUES ('DL','United States','Delta Air Lines Inc.');
INSERT INTO Airline VALUES ('UA','United States','United Air Lines Inc.');
INSERT INTO Airline VALUES ('LH','Germany','Lufthansa German Airlines');
INSERT INTO Airline VALUES ('AF','France','Compagnie Natl Air France');
INSERT INTO Airline VALUES ('BA','United Kingdom','British Airways Plc');
INSERT INTO Airline VALUES ('IB','Spain','Iberia Air Lines Of Spain');
INSERT INTO Airline VALUES ('WN','United States','Southwest Airlines Co.');
INSERT INTO Airline VALUES ('CZ','China','China Southern Airlines');
INSERT INTO Airline VALUES ('MU','China','China Eastern Airlines');
INSERT INTO Airline VALUES ('NH','Japan','All Nippon Airways Co.');
INSERT INTO Airline VALUES ('U2','United Kingdom','Easyjet Airline Company Limited');
INSERT INTO Airline VALUES ('FR','Ireland','Ryanair Ltd.');
INSERT INTO Airline VALUES ('TK','Turkey','Turkish Airlines Inc.');
INSERT INTO Airline VALUES ('CA','China','Air China');
INSERT INTO Airline VALUES ('EK','United Arab Emirates','Emirates');
INSERT INTO Airline VALUES ('AC','Canada','Air Canada');
INSERT INTO Airline VALUES ('QR','Qatar','Qatar Airways (Q.C.S.C)');
INSERT INTO Airline VALUES ('KL','Netherlands','Klm Royal Dutc');